CREATE TABLE IF NOT EXISTS "AnalyticsDaily" (
  "id" TEXT PRIMARY KEY,
  "day" TIMESTAMP(3) NOT NULL UNIQUE,
  "events" INTEGER NOT NULL DEFAULT 0,
  "uniqueVisitors" INTEGER NOT NULL DEFAULT 0,
  "postReads" INTEGER NOT NULL DEFAULT 0,
  "ctaClicks" INTEGER NOT NULL DEFAULT 0,
  "shares" INTEGER NOT NULL DEFAULT 0,
  "newsletterStarts" INTEGER NOT NULL DEFAULT 0,
  "newsletterConfirms" INTEGER NOT NULL DEFAULT 0,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
